pipeline {
    agent any

    environment {
        PATH = '/opt/apache-maven-3.9.8/bin:${env.PATH}'
    }
    
    stages {
        stage('Build1') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('The end') {
            steps {
                echo 'The end'
            }
        }
        stage('The end2') {
            steps {
                echo 'The end2'
            }
        }
    }
}
